name: EtherExp
version: '${project.version}'
main: org.example1.etherexp.EtherExp
api-version: '1.16'

commands:
  setBorderRadius:
  setBorderAngle:
  resetBorderAngle:
  resetBorderRadius:
  getWorld:
  penis:
  lobby:
  hub:
  setlobby:
  resetlobby:
  addtobanlist:
  removetobanlist:
  addtoadminlist:
  removetoadminlist:
  addOpAdmin:
  setchangeangle:
  stopborder:
  restartborder:
  banlist:
  adminlist:
  etherexp: